# **Bidding System**

In [1]:
#Samyukta Gurudanti

# **Basic Description**

In [2]:
#I have taken 5 stocks and 10 players for this example
#Each player would be assigned a random value from 1000 - 100000
#The player's money gets split randomly
#The random split money gets randomly assigned to a stock
#Where the rows indicate the stock name from 0-4
#The column name indicate the player name from 0-9
#The top 3 bidders get allocated the stock and that amount will be deducted from their wallet
#In the end all the stock names for each bidder is stored in a dictionary which is named as d
#Each player can get upto 3 stocks max, after which they will be out of the game by making their wallet to 0.0
#Where the key indicated the player name, and the value indicates the stock they have been randomly allocated with
#I have also made sure that the player does not get randomly assigned the same stock, be checking in the dictionaty again

# **Importing the Libraries**

In [3]:
import numpy as np
import pandas as pd
from random import choice

# **This is a function to split the amount the person has into 3 parts**

In [4]:
def split_num(n):
  parts = 3
  result = []
  for i in range(parts-1):
    x = np.random.randint(1,n-parts+i+1)
    n = n - x
    result.append(x)
  result.append(n)
  return result

In [5]:
split_arr = split_num(1734)

In [6]:
print(split_arr)

[61, 991, 682]


# **This is a function to allot the split amount to a stock**

In [7]:
#arr_not is the array containing all the aldready allocated to the players
def lister(arr_not,split_arr):
  index = generate_random(0,5,arr_not)
  new = [0,0,0,0,0] #Since there are 5 stocks
  for i in range(0,3):
    x = index[i]
    print(split_arr[i])
    new[index[i]] = new[index[i]]+split_arr[i]
  new = pd.Series(new)
  return new

In [8]:
def generate_random(start_range, end_range, arr_not):
  if len(arr_not)>=3:
    index = []
    for i in range(3):
      result = choice([i for i in range(start_range,end_range) if i not in arr_not])
      index.append(result)
  else:
    index = []
    arr_not = arr_not
    for i in range(3):
      result = choice([i for i in range(start_range,end_range) if i not in arr_not])
      index.append(result)
      arr_not.append(result)
  return index

In [9]:
generate_random(0,5,[1])

[4, 3, 2]

In [10]:
arr_not = [1,2]
hehe = lister(arr_not,split_arr)

61
991
682


# **This is a function to deduct**

This function would select the top 3 allocations and subtract it from the player, then bid would give the top three with others being zero

In [11]:
def b(deleted,arr_player):
  before = deleted
  final = []
  allocation = 3
  deleted = deleted.tolist()
  deleted.sort(reverse=True)
  deleted = deleted[:3]
  for i in range(len(before)):
    if before[i] in deleted:
      final.append(before[i])
    else:
      final.append(0)
  b = final
  arr_player = arr_player-final
  return [arr_player,b]

In [12]:
deleted = pd.Series(np.array([1279., 1284.  ,  0. , 343. ,3016., 5660. ,5239., 2309. ,   0., 1708.]))
arr_player = pd.Series(np.array([2828., 9964., 2105., 1948. ,3279., 6198., 9752. ,3817., 3473. ,9102.]))
x = b(deleted,arr_player)
y = x[0]
x = pd.Series(x[1])
print(y)
print(x)

0    2828.0
1    9964.0
2    2105.0
3    1948.0
4     263.0
5     538.0
6    4513.0
7    3817.0
8    3473.0
9    9102.0
dtype: float64
0       0.0
1       0.0
2       0.0
3       0.0
4    3016.0
5    5660.0
6    5239.0
7       0.0
8       0.0
9       0.0
dtype: float64


# **This is a function to check if all players have been allocated 3 stocks**

In [13]:
def checker(d):
  c = 0
  for i,v in d.items():
    actual_length = len(d)
    if len(v)==5:
      c+=1
  if c==actual_length:
    return 0
  else:
    return 1

# **Function to get arr_not from dictionary**

In [14]:
def get_not(d,player_name):
  val = d[player_name]
  if len(val)==0:
    return []
  elif len(val)==1:
    return list(map(int, val))
  else:
    val = val.split(',')
    arr_not = list(map(int, val))
    return arr_not

# **Function to insert bid to d**

In [15]:
def inserting_to_d(d,bid,stock_name):
  bid_dict = bid.to_dict()
  for i,v in bid_dict.items():
    if v>0:
      allo = str(stock_name)
      if len(d[i])<1:
        d[i] = allo
      else:
        d[i] = d[i]+','+allo
  return d

# **Delete players who have been allocated more than 3 stocks**

In [16]:
#Empty the pockets of players who have got 3 stocks
def delete_player(d,arr_player):
  for i,v in d.items():
    if len(v)==5:
      arr_player[i] = 0.0
  return arr_player

# **The Code**

In [17]:
#This is the array to record the allocations
d = dict()
for i in range(0,10):
  d[i] = ''
print(d)
#This is the array to store the recorded allocations
array2 = []
print(array2)
#This is the array for stocks
arr_stocks = np.zeros((5,10))
print(arr_stocks)
#This is the array for players
arr_player = pd.Series(np.zeros(10))
print(arr_player)

{0: '', 1: '', 2: '', 3: '', 4: '', 5: '', 6: '', 7: '', 8: '', 9: ''}
[]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    0.0
dtype: float64


In [18]:
for i in range(0,10):
  r = np.random.randint(1000,1000000)
  arr_player[i] = r
print('\n')
print('These are the allocated funds for the players')
print(arr_player)
print('\n')



These are the allocated funds for the players
0     61801.0
1      8882.0
2    842620.0
3    458413.0
4    483857.0
5    637726.0
6      3783.0
7    869571.0
8    747334.0
9    769358.0
dtype: float64




# **Start**

In [19]:
program = 1
round = 0
while program == 1:
  round +=1
  print('~~~~This is round',round,'~~~~')
  print('\n')
  #Allocation into the stockmarket
  for p_name in range(len(arr_player)):
    n = arr_player[p_name]
    print('This is the money of player',p_name)
    print(n)
    if n!=0.0:
      split_arr = split_num(n)
      print(split_arr,sum(split_arr))
      arr_not = get_not(d,p_name)
      a = lister(arr_not,split_arr)
      print('------')
      arr_stocks = pd.DataFrame(arr_stocks)
      arr_stocks[p_name] = a
    else:
      arr_stocks = pd.DataFrame(arr_stocks)
      arr_stocks[p_name] = [0.0,0.0,0.0,0.0,0.0]
      continue
  arr_stocks = arr_stocks.to_numpy()
  print('\n')
  print('This is the final allocation of stocks')
  print(arr_stocks)
  print('This is the sum for each stock')
  print(np.sum(arr_stocks, axis=1))

  #pick the largest stock from this
  summation = np.sum(arr_stocks, axis=1)
  largest = max(summation)
  print('\n')
  print('This is the largest amount')
  print(largest)
  print('This is the stock name')
  y = np.where(summation == largest)[0]
  stock_name = y[0]
  print(stock_name)
  deleted = arr_stocks[stock_name]
  print('\n')

  x = b(deleted,arr_player)
  arr_player = x[0]
  bid = x[1]
  print('This is the arr_player now')
  print(arr_player)
  print('This is bid')
  bid = pd.Series(bid)
  print(bid)
  print(d)

  d = inserting_to_d(d,bid,stock_name)
  print(d)
  arr_player = delete_player(d,arr_player)

  program = checker(d)

~~~~This is round 1 ~~~~


This is the money of player 0
61801.0
[1489, 34426, 25886.0] 61801.0
1489
34426
25886.0
------
This is the money of player 1
8882.0
[1142, 7216, 524.0] 8882.0
1142
7216
524.0
------
This is the money of player 2
842620.0
[819679, 14371, 8570.0] 842620.0
819679
14371
8570.0
------
This is the money of player 3
458413.0
[175392, 237208, 45813.0] 458413.0
175392
237208
45813.0
------
This is the money of player 4
483857.0
[395925, 84764, 3168.0] 483857.0
395925
84764
3168.0
------
This is the money of player 5
637726.0
[446868, 168815, 22043.0] 637726.0
446868
168815
22043.0
------
This is the money of player 6
3783.0
[3638, 81, 64.0] 3783.0
3638
81
64.0
------
This is the money of player 7
869571.0
[800388, 11828, 57355.0] 869571.0
800388
11828
57355.0
------
This is the money of player 8
747334.0
[197938, 338393, 211003.0] 747334.0
197938
338393
211003.0
------
This is the money of player 9
769358.0
[208233, 154128, 406997.0] 769358.0
208233
154128
406997.0
--

In [20]:
#Here are the player names and the stocks they got allocated to
d

{0: '2,0,3',
 1: '2,3,1',
 2: '1,4,0',
 3: '0,4,2',
 4: '1,2,4',
 5: '1,4,2',
 6: '0,2,3',
 7: '1,4,0',
 8: '1,0,2',
 9: '1,0,4'}